---
title: "06 - Meta-analysis as preregistered"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
library(brms)
library(tidybayes)
library(faux)
library(betapart)
library(modelr)
library(ggdist)
library(patchwork)
library(ggcorrplot)

my_seed <- 99
set.seed(my_seed)
b4ss_colors <- c(purple = "#8970FF", orange = "#FFA70B", pink = "#dd1c77")
```

# Read data

Here we read the `msa_models.rds` file which contains the estimates and standard errors obtained from refitting the analyses submitted by the teams.

```{r msa-models} 
msa_models <- readRDS("./data/analyses/msa_models.rds") %>%
  mutate(
    outcome = as.factor(outcome),
    typicality = as.factor(typicality),
    temporal_window = as.factor(temporal_window)
  ) %>%
  droplevels() %>%
  mutate(
    outcome = contr_code_sum(outcome),
    typicality = contr_code_sum(typicality),
    temporal_window = contr_code_sum(temporal_window)
  )
```

```{r meta-bm-prereg}
priors_prereg <- c(
  prior(normal(0, 1), class = Intercept),
  prior(cauchy(0, 1), class = sd)
)

meta_bm_prereg <- brm(
  estimate | se(se) ~ (1 | animal),
  data = msa_models,
  prior = priors_prereg,
  chain = 4,
  seed = my_seed,
  cores = 4,
  backend = "cmdstanr",
  threads = threading(2),
  file = "./data/meta_analysis/meta_bm_prereg.rds"
)
```

```{r meta-bm-prereg-summary}
meta_bm_prereg
```

# Analytic and researcher-related predictors model

Weakly-informative regularising priors.

```{r preds-priors}
preds_priors_prereg <- c(
  prior(normal(0, 1), class = Intercept),
  prior(normal(0, 1), class = b),
  prior(normal(0, 1), class = meanme),
  prior(cauchy(0, 1), class = sdme),
  prior(lkj(2), class = corme)
)
```

```{r predictors-bm}
# contrast code
msa_models <- msa_models %>% 
  mutate(
    # Measurement error cannot be 0 (model doesn't run), so adding a small number to it.
    all_sd = ifelse(is.na(all_sd), 0.0001, all_sd),
    years_from_phd_sd = ifelse(is.na(years_from_phd_sd) | years_from_phd_sd == 0, 0.0001, years_from_phd_sd),
    prior_belief_sd = ifelse(is.na(prior_belief_sd) | prior_belief_sd == 0, 0.0001, prior_belief_sd)
  ) 

predictors_bm_rintercepts_prereg <- brm(
  estimate | se(se) ~
    pop_sdi +
    n_random +
    n_models +
    outcome +                  # major dimension
    temporal_window +          # temporal window
    typicality +
    me(all_rating, all_sd) +
    me(years_from_phd, years_from_phd_sd) +
    me(prior_belief, prior_belief_sd),
  data = msa_models,
  prior = preds_priors_prereg,
  chain = 4,
  iter = 4000,
  control = list(adapt_delta = 0.9, max_treedepth = 13),
  seed = my_seed,
  cores = 4,
  threads = threading(2),
  backend = "cmdstanr",
  file = "./data/meta_analysis/predictors_bm_rintercepts_prereg.rds"
)

predictors_bm_rintercepts_prereg
```
