---
title: "DataViz for presentations"
author: "Timo Roettger"
date: "2022-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(ggalluvial)
library(here)
library(faux)

```

```{r load in, echo=FALSE}

#load in data
msa_models <- readRDS(here("./data/analyses/msa_models.rds")) %>%
  mutate(
    outcome = as.factor(outcome),
    typicality = as.factor(typicality),
    temporal_window = as.factor(temporal_window)
  ) %>%
  droplevels() %>%
  mutate(
    outcome = contr_code_sum(outcome),
    typicality = contr_code_sum(typicality),
    temporal_window = contr_code_sum(temporal_window)
  )

# unique models
msa_models_unique <- msa_models %>%
  select(animal, model_n, outcome, typicality_operationalization, framework, 
         model, temporal_window, random_effects, n_random, phon_rating, 
         stat_rating, n_predictors, pop_pred, operationalisation, 
         operationalisation_notes, found_effect) %>%
  distinct()

#aggregate
msa_models_unique_agg <- msa_models_unique %>% 
  select(-pop_pred) %>% 
  mutate(operationalisation = replace_na(operationalisation, "other"),
         temporal_window = replace_na(temporal_window, "other"),
         operationalisation = ifelse(operationalisation == "euclidean distance", 
                                     "other", operationalisation),
         operationalisation = ifelse(operationalisation == "unclear", 
                                     "other", operationalisation)) %>% 
  group_by(outcome,temporal_window,operationalisation,found_effect) %>% 
  count() %>% 
  mutate(highlight = ifelse(outcome == "f0", "f0", "no f0"))

```

```{r alluvium, echo=FALSE}

# ggaluvium 
flow_outcome <- 
ggplot(msa_models_unique_agg,
       aes(y = n, 
           axis1 = outcome, 
           axis2 = temporal_window,
           axis3 = operationalisation)) +
  geom_alluvium(aes(fill = outcome,
                    color = outcome),
                alpha = 0.7) +
  geom_stratum(fill = c("#323232", "grey",
                        "#107734", "#CC6677",
                        "#88CCEE",
                         rep("white", 14)),
               color = c("#323232", "grey",
                        "#107734", "#CC6677",
                        "#88CCEE",
                         rep("grey", 14)), 
               width = 1/3) +
  geom_text(stat = "stratum", 
            aes(label = after_stat(stratum)),
            color = c("white", "black",
                      "black", "black",
                      "black",
                       rep("black", 14))) +
  scale_x_discrete(limits = c("what?", "where?", "how?"), 
                   expand = c(.05, .05)) +
  scale_fill_manual(values = c("#88CCEE", "#CC6677",
                        "#107734", "grey",
                        "#323232")) +
  scale_color_manual(values = c("#88CCEE", "#CC6677",
                        "#107734", "grey",
                        "#323232")) +
  labs(y = "") +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=14))
flow_outcome

ggsave(filename = "figs/flow_outcome.png",
       plot = flow_outcome,
       device = "png",
       width = 150, 
       height = 110,
       units = "mm", 
       bg = "white",
       dpi = 500)

```

```{r alluvium2, echo=FALSE}

flow_outcome_f0 <- 
ggplot(msa_models_unique_agg,
       aes(y = n, 
           axis1 = outcome, 
           axis2 = temporal_window,
           axis3 = operationalisation)) +
  geom_alluvium(aes(fill = highlight,
                    color = highlight),
                alpha = 0.7) +
  geom_stratum(fill = c("white", "white",
                        "white", "#CC6677",
                        "white",
                         rep("white", 14)),
               color = c("grey", "grey",
                        "grey", "#CC6677",
                        "grey",
                         rep("grey", 14)), 
               width = 1/3) +
  geom_text(stat = "stratum", 
            aes(label = after_stat(stratum)),
            color = "black") +
  scale_x_discrete(limits = c("what?", "where?", "how?"), 
                   expand = c(.05, .05)) +
  scale_fill_manual(values = c("#CC6677",
                               alpha("white",0.1))) +
  scale_color_manual(values = c("#CC6677",
                               alpha("white",0.1))) +
  labs(y = "") +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=14))
flow_outcome_f0

ggsave(filename = "figs/flow_outcome_f0.png",
       plot = flow_outcome_f0,
       device = "png",
       width = 150, 
       height = 110,
       units = "mm", 
       bg = "white",
       dpi = 500)

# mapped onto effect
flow_outcome_result <- 
ggplot(msa_models_unique_agg,
       aes(y = n, 
           axis1 = outcome, 
           axis2 = temporal_window,
           axis3 = operationalisation,
           axis4 = found_effect)) +
  geom_alluvium(aes(fill = found_effect,
                    color = found_effect),
                alpha = 0.7) +
  geom_stratum(fill = c(rep("white", 19),
                         "#CC6677", "white"),
               color = c(rep("grey", 19),
                         "#CC6677", "grey"),,
               width = 1/3) +
  geom_text(stat = "stratum", 
            aes(label = after_stat(stratum)),
            color = "black") +
  scale_x_discrete(limits = c("what?", "where?", "how?", "effect?"), 
                   expand = c(.05, .05)) +
  scale_fill_manual(values = c(alpha("grey",0.2), "#CC6677")) +
  scale_color_manual(values = c(alpha("grey",0.2), "#CC6677")) +
  labs(y = "") +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.text.x = element_text(size=14))
flow_outcome_result

ggsave(filename = "figs/flow_outcome_f0.png",
       plot = flow_outcome_f0,
       device = "png",
       width = 150, 
       height = 110,
       units = "mm", 
       bg = "white",
       dpi = 500)

```



```{r meta-subsets}
msa_models <- msa_models %>% 
  mutate(found_effect = ifelse(is.na(found_effect), "no", found_effect),
         isolated_f0 = ifelse(outcome == "f0", 1, 0),
         isolated_noun = ifelse(specific_domain == "noun", 1, 0),
         f0_noun = ifelse(isolated_f0 == 1 & isolated_noun == 1, 1, 0))

slides_raw_est <- 
  ggplot(data = msa_models,
    aes(x = reorder(model_id, estimate), 
        y = estimate,
        color = found_effect,
        fill = found_effect
        )) +
  geom_hline(yintercept = 0, lty = "dotted") +
  geom_point(pch = 21,
             size = 0.8) +
  geom_segment(aes(xend = reorder(model_id, estimate), 
                   y = estimate - 1.96*se, 
                   yend = estimate + 1.96*se),
                lineend = "round",
                size = 1,
                alpha = 0.5) +
  scale_x_discrete(expand =  c(0.05,0.05)) + 
  scale_y_continuous(limits =  c(-2, 2.2)) + 
  labs(# title = "Effect estimates across all submitted effects",
       caption = "Reports statistically reliable effect (orange),
       Reports null result (black)\n",
       x = "Submitted typicality effect", 
       y = "Standardized posterior effect size\n") +
  scale_color_manual(values = c("black", "#ef8a62")) +
  scale_fill_manual(values = c("black", "#ef8a62")) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        plot.caption = element_text(vjust = -5)
        )
slides_raw_est

ggsave(filename = "figs/slides_raw_est.png",
       plot = slides_raw_est,
       device = "png",
       width = 150, 
       height = 85,
       units = "mm", 
       dpi = 500)

# ONLY F0
slides_raw_est_f0 <- 
  ggplot(data = msa_models,
    aes(x = reorder(model_id, estimate), 
        y = estimate,
        color = as.factor(isolated_f0)
        )) +
  geom_hline(yintercept = 0, lty = "dotted") +
  geom_point(pch = 21,
             size = 0.8) +
  geom_segment(aes(xend = reorder(model_id, estimate), 
                   y = estimate - 1.96*se, 
                   yend = estimate + 1.96*se),
                lineend = "round",
                size = 1,
                alpha = 0.5) +
  scale_x_discrete(expand =  c(0.05,0.05)) + 
  scale_y_continuous(limits =  c(-2, 2.2)) + 
  labs(# title = "Effect estimates across all submitted effects",
       caption = "Analysis based on f0 (blue),
       Analyes based on different outcomes (grey)\n",
       x = "Submitted typicality effect", 
       y = "Standardized posterior effect size\n") +
  scale_color_manual(values = c("grey", "navyblue")) +
  scale_fill_manual(values = c("grey", "navyblue")) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        plot.caption = element_text(vjust = -5)
        )
slides_raw_est_f0

ggsave(filename = "figs/slides_raw_est_f0.png",
       plot = slides_raw_est_f0,
       device = "png",
       width = 150, 
       height = 85,
       units = "mm", 
       dpi = 500)


# ONLY F0
slides_raw_est_f0_noun <- 
  ggplot(data = msa_models,
    aes(x = reorder(model_id, estimate), 
        y = estimate,
        color = as.factor(f0_noun)
        )) +
  geom_hline(yintercept = 0, lty = "dotted") +
  geom_point(pch = 21,
             size = 0.8) +
  geom_segment(aes(xend = reorder(model_id, estimate), 
                   y = estimate - 1.96*se, 
                   yend = estimate + 1.96*se),
                lineend = "round",
                size = 1,
                alpha = 0.5) +
  scale_x_discrete(expand =  c(0.05,0.05)) + 
  scale_y_continuous(limits =  c(-2, 2.2)) + 
  labs(# title = "Effect estimates across all submitted effects",
       caption = "Analysis based on f0 in the noun (blue),
       Analyes based on other measures (grey)\n",
       x = "Submitted typicality effect", 
       y = "Standardized posterior effect size\n") +
  scale_color_manual(values = c("grey", "navyblue")) +
  scale_fill_manual(values = c("grey", "navyblue")) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line = element_blank(),
        plot.caption = element_text(vjust = -5)
        )
slides_raw_est_f0_noun

ggsave(filename = "figs/slides_raw_est_f0_noun.png",
       plot = slides_raw_est_f0_noun,
       device = "png",
       width = 150, 
       height = 85,
       units = "mm", 
       dpi = 500)
```

