---
title: "OSF management"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
library(osfr)
```

# Manage OSF with osfr

This document contains the code used to manage the OSF repo with the [osfr](https://docs.ropensci.org/osfr/) package.

# Retrieve OSF repo and components

```{r retrieve}
# Main repo "Many Speech Analysis": https://osf.io/3bmcp/
osf_repo <- osf_retrieve_node("3bmcp")
# Repo components
osf_comps <- osf_ls_nodes(osf_repo)
# Dataset & Materials component
data_comp <- osf_comps %>% filter(name == "Data")
```

# List data_comp files

```{r data_files}
osf_ls_files(data_comp)
```

# Readme files

## Knit Readmes

We can knit the readme files (they are GitHub documents, i.e. `.Rmd` files that are converted to `.md` files upon knitting).

```{r knit-all, message=FALSE, warning=FALSE}
files <- list.files("./osf/data", pattern = "[.]Rmd$", recursive = T, full.names = T)

for (f in files) {
  xfun::Rscript_call(rmarkdown::render, list(f))
}
```

## Upload Readmes to the OFS repo

```{r readmes}
# A loop would be better

# data/ ----
osf_upload(data_comp, path = "./osf/data/README.md", conflicts = "overwrite", verbose = T)

data_comp_files <- osf_ls_files(data_comp)



# data/norming/ ----
raw <- data_comp_files %>% filter(name == "norming")

#### delete old readme ("overwrite" option fails)
old_readme <- osf_ls_files(data_comp, "norming", pattern = "README.md")
osf_rm(old_readme, check = FALSE)

#### upload new readme
osf_upload(
  raw,
  path = "./osf/data/norming/README.md",
  conflicts = "overwrite", verbose = T)



# data/norming/images/ ----
#### delete old readme
old_readme <- osf_ls_files(data_comp, "norming/images/", pattern = "README.md")
osf_rm(old_readme, check = FALSE)

#### upload new readme
audio <- osf_ls_files(data_comp, "norming", pattern = "images")
osf_upload(
  audio,
  path = "./osf/data/norming/images/README.md",
  conflicts = "overwrite", verbose = T)



# data/production/audio/ ----
#### delete old readme
# old_readme <- osf_ls_files(data_comp, "production/audio", pattern = "README.md")
# osf_rm(old_readme, check = FALSE)
# 
# #### upload new readme
# audio <- osf_ls_files(data_comp, "production", pattern = "audio")
# osf_upload(
#   audio,
#   path = "./osf/data/production/audio/README.md",
#   conflicts = "overwrite", verbose = T)



# data/production/trial-lists ----
#### delete old readme
# old_readme <- osf_ls_files(data_comp, "production/trial-lists", pattern = "README.md")
# osf_rm(old_readme, check = FALSE)
# 
# #### upload new readme
# trials <- osf_ls_files(data_comp, "production", pattern = "trial-lists")
# osf_upload(
#   trials,
#   path = "./osf/data/production/trial-lists/README.md",
#   conflicts = "overwrite", verbose = T)
```

# TextGrids

```{r textgrids, eval=FALSE}
audio <- osf_ls_files(data_comp, "production", pattern = "audio")

# delete old tgs
old_tgs <- osf_ls_files(audio, pattern = ".TextGrid", n_max = Inf)

for (file in 1:nrow(old_tgs)) {
  osf_rm(old_tgs[file,], check = FALSE)
}

# upload new tgs
new_tgs <- list.files("./osf/data/production/audio/", ".TextGrid", full.names = TRUE)

for (tg in new_tgs) {
  osf_upload(
    audio,
    path = tg,
    conflicts = "overwrite", verbose = T
  )
}
```

# Trial lists

```{r tlists}
tlists <- list.files("./data/trial-lists", ".csv", full.names = TRUE)
typ <- read_csv("./data/dataset/typicality.csv")

for (tlist in tlists) {
  speaker <- str_sub(tlist, 20, 21)
  tbl <- read_csv(tlist) %>%
    mutate(
      speaker = speaker,
      trial = row_number()
    ) %>%
    left_join(y = typ) %>%
    select(speaker, trial, condition, typicality, everything())
  
  write_csv(tbl, file = paste0("./osf/data/production/trial-lists/", speaker, ".csv"))
}
```

```{r tlists-upload}
trials <- osf_ls_files(data_comp, "production", pattern = "trial-lists")

# delete old trials
old_trials <- osf_ls_files(trials, pattern = ".csv", n_max = Inf)

for (file in 1:nrow(old_trials)) {
  osf_rm(old_trials[file,], check = FALSE)
}

# upload new trials
new_trials <- list.files("./osf/data/production/trial-lists/", ".csv", full.names = TRUE)

for (trial in new_trials) {
  osf_upload(
    trials,
    path = trial,
    conflicts = "overwrite", verbose = T
  )
}
```

