name: Manage issues

on:
  issues:
    types: [opened, labeled, assigned]

jobs:
  set-meeting-label:
    name: Set label of Meeting issues to meetings
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        if: github.event.action == 'opened'
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Meeting"], "labels": ["meeting"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
