name: "Set issue label"
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[ {"keywords": ["Minutes"], "labels": ["meetings"]} ]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
